-- MySQL Script generated by MySQL Workbench
-- 12/06/16 21:34:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ChangeThisName
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema testdatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testdatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testdatabase` DEFAULT CHARACTER SET utf8 ;
USE `testdatabase` ;

-- -----------------------------------------------------
-- Table `testdatabase`.`accounttype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdatabase`.`accounttype` (
  `type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`type`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `testdatabase`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdatabase`.`user` (
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `account-type` VARCHAR(45) NOT NULL DEFAULT 'Default',
  PRIMARY KEY (`username`),
  UNIQUE INDEX `email` (`email` ASC),
  INDEX `fk_account_type_idx` (`account-type` ASC),
  CONSTRAINT `fk_account_type`
    FOREIGN KEY (`account-type`)
    REFERENCES `testdatabase`.`accounttype` (`type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `testdatabase`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdatabase`.`event` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `header` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `startDateTime` DATETIME NOT NULL,
  `endDateTime` DATETIME NOT NULL,
  `location` VARCHAR(60) NULL DEFAULT NULL,
  `owner` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Owner_idx` (`owner` ASC),
  CONSTRAINT `Owner`
    FOREIGN KEY (`owner`)
    REFERENCES `testdatabase`.`user` (`username`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `testdatabase`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdatabase`.`log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(20) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `targetUser` VARCHAR(50) NOT NULL,
  `log_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 74
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `testdatabase`.`sharedevent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdatabase`.`sharedevent` (
  `ShareID` INT(11) NOT NULL AUTO_INCREMENT,
  `eventID` INT(11) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ShareID`),
  UNIQUE INDEX `personUnique` (`eventID` ASC, `username` ASC),
  INDEX `shared_with_fk_idx` (`username` ASC),
  CONSTRAINT `eventid`
    FOREIGN KEY (`eventID`)
    REFERENCES `testdatabase`.`event` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `shared_with_fk`
    FOREIGN KEY (`username`)
    REFERENCES `testdatabase`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `testdatabase`.`useraccess`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdatabase`.`useraccess` (
  `username` VARCHAR(20) NOT NULL,
  `token` VARCHAR(45) NOT NULL,
  `createdToken` DATETIME NOT NULL,
  PRIMARY KEY (`username`),
  CONSTRAINT `username`
    FOREIGN KEY (`username`)
    REFERENCES `testdatabase`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `testdatabase`.`accounttype`
-- -----------------------------------------------------
START TRANSACTION;
USE `testdatabase`;
INSERT INTO `testdatabase`.`accounttype` (`type`) VALUES ('Default');
INSERT INTO `testdatabase`.`accounttype` (`type`) VALUES ('Admin');

COMMIT;

