-- MySQL Script generated by MySQL Workbench
-- 10/31/16 20:47:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema testdatabase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `testdatabase` ;

-- -----------------------------------------------------
-- Schema testdatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testdatabase` DEFAULT CHARACTER SET utf8 ;
USE `testdatabase` ;

-- -----------------------------------------------------
-- Table `testdatabase`.`accounttype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdatabase`.`accounttype` ;

CREATE TABLE IF NOT EXISTS `testdatabase`.`accounttype` (
  `type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdatabase`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdatabase`.`user` ;

CREATE TABLE IF NOT EXISTS `testdatabase`.`user` (
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `account-type` VARCHAR(45) NOT NULL DEFAULT 'Default',
  PRIMARY KEY (`username`),
  UNIQUE INDEX `email` (`email` ASC),
  INDEX `fk_account_type_idx` (`account-type` ASC),
  CONSTRAINT `fk_account_type`
    FOREIGN KEY (`account-type`)
    REFERENCES `testdatabase`.`accounttype` (`type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdatabase`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdatabase`.`event` ;

CREATE TABLE IF NOT EXISTS `testdatabase`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `header` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `startDateTime` DATETIME NOT NULL,
  `endDateTime` DATETIME NOT NULL,
  `location` VARCHAR(60) NULL,
  `owner` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Owner_idx` (`owner` ASC),
  CONSTRAINT `Owner`
    FOREIGN KEY (`owner`)
    REFERENCES `testdatabase`.`user` (`username`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdatabase`.`sharedevent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdatabase`.`sharedevent` ;

CREATE TABLE IF NOT EXISTS `testdatabase`.`sharedevent` (
  `ShareID` INT NOT NULL AUTO_INCREMENT,
  `eventID` INT NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  UNIQUE INDEX `personUnique` (`eventID` ASC, `username` ASC),
  INDEX `shared_with_fk_idx` (`username` ASC),
  PRIMARY KEY (`ShareID`),
  CONSTRAINT `eventid`
    FOREIGN KEY (`eventID`)
    REFERENCES `testdatabase`.`event` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `shared_with_fk`
    FOREIGN KEY (`username`)
    REFERENCES `testdatabase`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdatabase`.`useraccess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdatabase`.`useraccess` ;

CREATE TABLE IF NOT EXISTS `testdatabase`.`useraccess` (
  `username` VARCHAR(20) NOT NULL,
  `token` VARCHAR(45) NOT NULL,
  `createdToken` DATETIME NOT NULL,
  PRIMARY KEY (`username`),
  CONSTRAINT `username`
    FOREIGN KEY (`username`)
    REFERENCES `testdatabase`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
